name: Build and Test multi-os

on: [push, pull_request] # todo: when on master, remove push

env:
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  build:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }} # modify and use to wait for lint and test finish
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.9] #3.7, 3.8

    runs-on: ${{ matrix.os }}

    name: Build PyInstaller executable ${{ matrix.os }} + Py ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: pip install poetry

    - name: Get packages via poetry
      run: poetry install

#    Possibility to add chrome to the executable, but add 100mb+
#    - name: Install playwright
#      run: |
#        poetry run python -m playwright install chrome

    - name: Create date env variable
      shell: bash
      run: |
        echo "today=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Get CTVBot version number
      uses: SebRollen/toml-action@v1.0.0
      id: read_toml
      with:
        file: 'pyproject.toml'
        field: 'tool.poetry.version'

    - name: Build executable
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          poetry run pyinstaller main_gui.py --onefile --add-binary "ctvbot_logo.ico;." --add-binary "pyproject.toml;." --icon ctvbot_logo.ico --name CTVBot_Test_${{steps.read_toml.outputs.value}}_${{env.today}}_${{runner.os}}
        else
          poetry run pyinstaller main_gui.py --onefile --add-binary "ctvbot_logo.ico:." --add-binary "pyproject.toml:." --icon ctvbot_logo.ico --name CTVBot_Test_${{steps.read_toml.outputs.value}}_${{env.today}}_${{runner.os}}.bin
        fi
        mv ./proxy/ ./dist/
      shell: bash

    - name: Upload artifact ${{ matrix.os }}
      uses: actions/upload-artifact@v1
      with:
        name: CTVBot_Test_${{ steps.read_toml.outputs.value }}_${{ env.today }}_${{ runner.os }}
        path: dist/
