name: Pytest Action

on: [push, pull_request]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] #, macos-latest]
        python-version: [3.8] #3.7, 3.8

    runs-on: ${{ matrix.os }}

    name: Test ${{ matrix.os }} + Py ${{ matrix.python-version }} + ${{ github.ref }} + ${{github.base_ref}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        ls
    - name: Unit tests with pytest
      run: |
        poetry run python -m pytest tests/